### ISSUE TITLE
Unable to resolve action `twiddler/is-my-docker-parent-image-out-of-date@v1`, unable to find version `v1`

### ISSUE THREAD

**Issue by marius** [twiddler/is-my-docker-parent-image-out-of-date#1]
Hi,

I get the this error when following the instructions in the README:
Unable to resolve action `twiddler/is-my-docker-parent-image-out-of-date@v1`, unable to find version `v1`

Cheers
Marius

**Comment by twiddler** [comment]
Was missing the v1 tag. Thought GitHub would resolve that intelligently by itself from v1.0.0 and so forth. Should be working now. :+1:
