### ISSUE TITLE
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.

### ISSUE THREAD

**Issue by MentalFS** [twiddler/is-my-docker-parent-image-out-of-date#4]
Github prints this warning when `Run twiddler/is-my-docker-parent-image-out-of-date@v1` is executed:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by ibotty** [comment]
This only needs a new version (tag) I assume, right?

**Comment by twiddler** [comment]
Could you open a pull request with the necessary changes?

**Comment by araines** [comment]
Looks like there are no changes that need to be made, just that it needs a new version releasing - the code on `main` looks fine to me, but `v1` doesn't contain the required changes.

**Comment by twiddler** [comment]
I haven't looked at this in a long time. I just ran the tests and I think you're right. I can look into this at the end of the week in more detail.

**Comment by twiddler** [comment]
Just released https://github.com/twiddler/is-my-docker-parent-image-out-of-date/releases/tag/v1.0.1. Please let me know if something's not right. I haven't touched this code in a long time, and I currently don't use this action myself.
